import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return(
    <html lang="en" className="dark">
      <Script src="https://kit.fontawesome.com/6d540836f0.js" />
      <body className={inter.className}>
        <Providers>
          { children }
        </Providers>
      </body>
    </html>
  );
}

